# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Argonap < Formula
  desc "A CLI to configure/clear SyncWindows on ArgoCD projects."
  homepage "https://github.com/ivanklee86/argonap"
  version "0.0.1"

  on_macos do
    on_intel do
      url "https://github.com/ivanklee86/argonap/releases/download/v0.0.1/argonap_0.0.1_darwin_amd64.tar.gz"
      sha256 "a1cd4c5e5f58f738137368b45ab73364e0787d7f3bb9d6cb7bf6531a22e97a5f"

      def install
        bin.install "argonap"
      end
    end
    on_arm do
      url "https://github.com/ivanklee86/argonap/releases/download/v0.0.1/argonap_0.0.1_darwin_arm64.tar.gz"
      sha256 "eccfb8190c6444328b5da53027ea664d2bb08d6323a59d1ace72489e8bdbb503"

      def install
        bin.install "argonap"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ivanklee86/argonap/releases/download/v0.0.1/argonap_0.0.1_linux_amd64.tar.gz"
        sha256 "54be0534501b438c181070d58b47c2633cd2bbc491f8dd5c3ba8bb93bd986e0b"

        def install
          bin.install "argonap"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ivanklee86/argonap/releases/download/v0.0.1/argonap_0.0.1_linux_arm64.tar.gz"
        sha256 "83bd41018ec3143d39a315d183aaf98341d628d8d9e0418018615e7dd55d99b5"

        def install
          bin.install "argonap"
        end
      end
    end
  end
end
