# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Argonap < Formula
  desc "A CLI to configure/clear SyncWindows on ArgoCD projects."
  homepage "https://github.com/ivanklee86/argonap"
  version "0.0.1"

  on_macos do
    on_intel do
      url "https://github.com/ivanklee86/argonap/releases/download/v0.0.1/argonap_0.0.1_darwin_amd64.tar.gz"
      sha256 "4208b0e5d7bb92dbed14c475056b4ad39b65b8714b9674027a9bb4158a3317f6"

      def install
        bin.install "argonap"
      end
    end
    on_arm do
      url "https://github.com/ivanklee86/argonap/releases/download/v0.0.1/argonap_0.0.1_darwin_arm64.tar.gz"
      sha256 "b2e9caea85a0d984bcf5765864d6e4f32e75775cb5bb6206727b5dca2ebefc07"

      def install
        bin.install "argonap"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ivanklee86/argonap/releases/download/v0.0.1/argonap_0.0.1_linux_amd64.tar.gz"
        sha256 "806c7f8c146818a8b1fb66c1dbdf8566ab57a72b308ba13fa03b3ef8a799ff4a"

        def install
          bin.install "argonap"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ivanklee86/argonap/releases/download/v0.0.1/argonap_0.0.1_linux_arm64.tar.gz"
        sha256 "0d77684ca856b02d5c552383c87bc651d5225ccedfd01e8eea5950ae460d80ae"

        def install
          bin.install "argonap"
        end
      end
    end
  end
end
