# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Argonap < Formula
  desc "A CLI to configure/clear SyncWindows on ArgoCD projects."
  homepage "https://github.com/ivanklee86/argonap"
  version "0.0.3"

  on_macos do
    on_intel do
      url "https://github.com/ivanklee86/argonap/releases/download/v0.0.3/argonap_0.0.3_darwin_amd64.tar.gz"
      sha256 "cccb9dcc6780899cd191b2983926723798d88201489006f24456574b99bd38d4"

      def install
        bin.install "argonap"
      end
    end
    on_arm do
      url "https://github.com/ivanklee86/argonap/releases/download/v0.0.3/argonap_0.0.3_darwin_arm64.tar.gz"
      sha256 "6f92562cfa38793c120d98d73bd8c80ad5f3a35f358d043aee9a9ac0056af205"

      def install
        bin.install "argonap"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ivanklee86/argonap/releases/download/v0.0.3/argonap_0.0.3_linux_amd64.tar.gz"
        sha256 "3b3bfc4d478d46fb8bdd7e1e95c51d066dc2016d692d1d4adcdd97ca15c19755"

        def install
          bin.install "argonap"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ivanklee86/argonap/releases/download/v0.0.3/argonap_0.0.3_linux_arm64.tar.gz"
        sha256 "305791a4271dfc02ba31584feb4ccd04ac6f899528976551435b363558957c79"

        def install
          bin.install "argonap"
        end
      end
    end
  end
end
