# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Argonap < Formula
  desc "A CLI to configure/clear SyncWindows on ArgoCD projects."
  homepage "https://github.com/ivanklee86/argonap"
  version "0.0.1"

  on_macos do
    on_intel do
      url "https://github.com/ivanklee86/argonap/releases/download/v0.0.1/argonap_0.0.1_darwin_amd64.tar.gz"
      sha256 "53db2b81fabc926a5840e1e512cf84790b88e785ff1ebc79cf9218a9641b8b28"

      def install
        bin.install "argonap"
      end
    end
    on_arm do
      url "https://github.com/ivanklee86/argonap/releases/download/v0.0.1/argonap_0.0.1_darwin_arm64.tar.gz"
      sha256 "2f129e66a0821fab019884b4f89fcf010234a07481b4e700b922c8a281d67c90"

      def install
        bin.install "argonap"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ivanklee86/argonap/releases/download/v0.0.1/argonap_0.0.1_linux_amd64.tar.gz"
        sha256 "ebe745b6e5b2a1466bbc22740ea35b00ae0579ab818e5f1bbececbb33ee0b9b8"

        def install
          bin.install "argonap"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ivanklee86/argonap/releases/download/v0.0.1/argonap_0.0.1_linux_arm64.tar.gz"
        sha256 "76ccc071d7663a42e4d63ac9ac0b9a7e5b204edb8b43f0c53d80d39c359f9534"

        def install
          bin.install "argonap"
        end
      end
    end
  end
end
