# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TangleCli < Formula
  desc "A CLI to configure/clear SyncWindows on ArgoCD projects."
  homepage "https://github.com/ivanklee86/tangle-cli"
  version "0.0.8"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ivanklee86/tangle/releases/download/v0.0.8/tangle_0.0.8_darwin_amd64.tar.gz"
      sha256 "85bf5ab8636bf200363c843207f01440a28e9a165599a9de0e28d4fbca311aaf"

      def install
        bin.install "tangle-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ivanklee86/tangle/releases/download/v0.0.8/tangle_0.0.8_darwin_arm64.tar.gz"
      sha256 "36a19169795a47565488333a2d8498059b1c566862558b12a58680dc4690b616"

      def install
        bin.install "tangle-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ivanklee86/tangle/releases/download/v0.0.8/tangle_0.0.8_linux_amd64.tar.gz"
        sha256 "4154f7831789328c7708dbbf934ea8a258e2051f34d18bcd02d5f0d2195ef197"

        def install
          bin.install "tangle-cli"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ivanklee86/tangle/releases/download/v0.0.8/tangle_0.0.8_linux_arm64.tar.gz"
        sha256 "042d45f96b073eb94390020be71eb742a77917cb6679af0fb40b1e888bcf1a3d"

        def install
          bin.install "tangle-cli"
        end
      end
    end
  end
end
